[package]
name = "kailua-host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
clap.workspace = true
hashbrown = { workspace = true, features = ["rayon"] }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

# Alloy
alloy = { workspace = true, features = ["rlp", "reqwest"] }
alloy-primitives = { workspace = true, features = ["map-hashbrown"] }
alloy-chains.workspace = true
alloy-eips.workspace = true
op-alloy-genesis.workspace = true
op-alloy-protocol.workspace = true
op-alloy-registry.workspace = true

# Kailua
kailua-build.workspace = true
kailua-client.workspace = true
kailua-common.workspace = true

# Kona
kona-client.workspace = true
kona-derive.workspace = true
kona-host.workspace = true
kona-preimage.workspace = true

# zkVM
bonsai-sdk.workspace = true
risc0-zkvm.workspace = true

# Zeth
zeth-core.workspace = true
zeth-core-optimism.workspace = true
zeth-preflight.workspace = true
zeth-preflight-optimism.workspace = true
