[workspace]
resolver = "2"
members = [
    "bin/*",
    "build/*",
    "crates/*",
]

[workspace.dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
bincode = "1.3.3"
bytemuck = "1.12"
bytes = "1.7.2"
clap = { version = "4.5.21", features = ["derive", "env"] }
c-kzg = "1.0.2"
ethers = "2.0.14"
foundry-compilers = "0.11.0"
hashbrown = "0.15.0"
hex = "0.4.3"
lazy_static = "1.5.0"
lru = "0.12.4"
pot = "3.0.1"
semver = "1.0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.127"
spin = { version = "0.9.8", features = ["mutex"] }
tempfile = "3.10.1"
tokio = { version = "1.39.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Alloy
alloy = { version = "0.5.4", default-features = false, features = ["json"] }
alloy-chains = "0.1.46"
alloy-consensus = "0.5.4"
alloy-eips = { version = "0.5.4", features = ["kzg"] }
alloy-primitives = { version = "0.8", default-features = false }
alloy-provider = "0.5.4"
alloy-rlp = "0.3.8"
alloy-rpc-types-beacon = "0.5.4"
op-alloy-genesis = { version = "0.5.2", default-features = false }
op-alloy-consensus = { version = "0.5.2", default-features = false }
op-alloy-protocol = { version = "0.5.2", default-features = false }

# Kailua
kailua-build = { path = "build/risczero" }
kailua-client = { path = "bin/client" }
kailua-common = { path = "crates/common" }
kailua-contracts = { path = "crates/contracts" }
kailua-host = { path = "bin/host" }

# Kona git = "https://github.com/ethereum-optimism/kona", rev = "2e943f4"
kona-client = { git = "https://github.com/hashcashier/kona", branch = "kailua" }
kona-common = { git = "https://github.com/hashcashier/kona", branch = "kailua" }
kona-common-proc = { git = "https://github.com/hashcashier/kona", branch = "kailua" }
kona-derive = { git = "https://github.com/hashcashier/kona", branch = "kailua", default-features = false, features = ["serde"] }
kona-driver = { git = "https://github.com/hashcashier/kona", branch = "kailua" }
kona-executor = { git = "https://github.com/hashcashier/kona", branch = "kailua" }
kona-host = { git = "https://github.com/hashcashier/kona", branch = "kailua" }
kona-mpt = { git = "https://github.com/hashcashier/kona", branch = "kailua", features = ["serde"] }
kona-preimage = { git = "https://github.com/hashcashier/kona", branch = "kailua", features = ["rkyv"] }

# RISC Zero zkVM
risc0-build = { version = "1.1.3" }
risc0-ethereum-contracts = "1.1.0"
risc0-zkvm = { version = "1.1.3", features = ["heap-embedded-alloc"] }
risc0-zkvm-platform = { version = "1.1.3", features = ["heap-embedded-alloc"] }

# RISC Zero Zeth
zeth-core = { git = "https://github.com/risc0/zeth", branch = "rkhalil/reth" }
zeth-core-optimism = { git = "https://github.com/risc0/zeth", branch = "rkhalil/reth" }
zeth-preflight = { git = "https://github.com/risc0/zeth", branch = "rkhalil/reth" }
zeth-preflight-optimism = { git = "https://github.com/risc0/zeth", branch = "rkhalil/reth" }

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

[patch.crates-io]
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.3-risczero.0" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
#c-kzg = { git = "https://github.com/risc0/c-kzg-4844.git", branch = "risc0" }
