[workspace]
resolver = "2"
members = [
    "bin/*",
    "build/*",
    "crates/*",
]

[workspace.dependencies]
alloy = { version = "0.3.1", default-features = false, features = ["json"] }
#alloy-contract = { version = "0.3.3", features = ["pubsub"] }
alloy-consensus = "0.3.1"
alloy-eips = { version = "0.3.1", features = ["kzg"] }
alloy-primitives = { version = "0.8", default-features = false }
alloy-provider = "0.3.1"
#alloy-sol-types = { version = "0.8.3", features = ["json"] }
alloy-rpc-types-beacon = "0.3.6"
anyhow = "1.0.86"
async-trait = "0.1.81"
bincode = "1.3.3"
bytemuck = "1.12"
bytes = "1.7.2"
clap = "4.5.11"
c-kzg = "1.0.2"
ethers = "2.0.14"
foundry-compilers = "0.11.0"
hex = "0.4.3"
lazy_static = "1.5.0"
lru = "0.12.4"
op-alloy-consensus = { version = "0.2", default-features = false }
op-alloy-protocol = { version = "0.2", default-features = false }
revm = { git = "https://github.com/bluealloy/revm", tag = "v37", version = "10.0.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.127"
superchain-primitives = "0.3.4"
spin = { version = "0.9.8", features = ["mutex"] }
tempfile = "3.10.1"
tokio = { version = "1.39.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Kailua
kailua-build = { path = "build/risczero" }
kailua-client = { path = "bin/client" }
kailua-common = { path = "crates/common" }
kailua-contracts = { path = "crates/contracts" }
kailua-host = { path = "bin/host" }

# Kona "https://github.com/ethereum-optimism/kona"
kona-client = { git = "https://github.com/hashcashier/kona", rev = "07b052c" }
kona-common = { git = "https://github.com/hashcashier/kona", rev = "07b052c" }
kona-common-proc = { git = "https://github.com/hashcashier/kona", rev = "07b052c" }
kona-derive = { git = "https://github.com/hashcashier/kona", rev = "07b052c", default-features = false }
kona-executor = { git = "https://github.com/hashcashier/kona", rev = "07b052c" }
kona-host = { git = "https://github.com/hashcashier/kona", rev = "07b052c" }
kona-mpt = { git = "https://github.com/hashcashier/kona", rev = "07b052c" }
kona-preimage = { git = "https://github.com/hashcashier/kona", rev = "07b052c", features = ["rkyv"] }
kona-primitives = { git = "https://github.com/hashcashier/kona", rev = "07b052c" }

# RISC Zero
risc0-build = { version = "1.1.2" }
risc0-ethereum-contracts = "1.1.0"
risc0-zkvm = { version = "1.1.2", features = ["heap-embedded-alloc"] }
risc0-zkvm-platform = { version = "1.1.2", features = ["heap-embedded-alloc"] }

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

[patch.crates-io]
op-alloy-protocol = { git = "https://github.com/alloy-rs/op-alloy", rev = "0d8ef62" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.3-risczero.0" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
#c-kzg = { git = "https://github.com/risc0/c-kzg-4844.git", branch = "risc0" }
