[package]
name = "kailua-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true, features = ["contract", "rlp", "json"]}
foundry-compilers.workspace = true

[build-dependencies]
foundry-compilers.workspace = true
semver.workspace = true