[package]
name = "kailua-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true, features = ["contract", "rlp", "json", "sol-types"]}
alloy-sol-types.workspace = true
foundry-compilers.workspace = true

[build-dependencies]
foundry-compilers.workspace = true
