[package]
name = "kailua-client"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true, features = ["full", "kzg"] }
alloy-rpc-types-beacon.workspace = true
alloy-primitives = { workspace = true, features = ["map-hashbrown"] }
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
bytemuck.workspace = true
bytes.workspace = true
c-kzg.workspace = true
clap.workspace = true
lru.workspace = true

kailua-build.workspace = true
kailua-common.workspace = true

kona-derive.workspace = true
kona-host.workspace = true
kona-preimage.workspace = true
kona-proof.workspace = true
kona-std-fpvm.workspace = true

risc0-zkvm.workspace = true

serde.workspace = true
spin.workspace = true
tracing.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
