[package]
name = "kailua-client"
version = "0.3.0-alpha.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
bytemuck.workspace = true
c-kzg.workspace = true
clap.workspace = true
hex.workspace = true
rkyv.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true

opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-prometheus.workspace = true
opentelemetry-zipkin.workspace = true

alloy = { workspace = true, features = ["full", "kzg"] }
alloy-primitives = { workspace = true, features = ["map-hashbrown"] }

kailua-build.workspace = true
kailua-common.workspace = true
kailua-contracts.workspace = true

kona-derive.workspace = true
kona-host.workspace = true
kona-preimage.workspace = true
kona-proof.workspace = true
kona-protocol.workspace = true
kona-std-fpvm.workspace = true

bonsai-sdk.workspace = true
boundless-market.workspace = true
risc0-aggregation.workspace = true
risc0-ethereum-contracts.workspace = true
risc0-zkvm.workspace = true

[features]
prove = [
    "risc0-zkvm/prove"
]
