[package]
name = "kailua-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
bytemuck.workspace = true
c-kzg.workspace = true
hashbrown.workspace = true
lazy_static.workspace = true
lru.workspace = true
spin.workspace = true

alloy-consensus = { workspace = true, features = ["serde"] }
alloy-eips.workspace = true
alloy-primitives = { workspace = true, features = ["map-hashbrown"] }
alloy-rpc-types-beacon.workspace = true
op-alloy-consensus = { workspace = true, features = ["serde"] }
op-alloy-genesis = { workspace = true, features = ["serde"] }
op-alloy-protocol = { workspace = true, features = ["serde"] }

kona-client.workspace = true
kona-common.workspace = true
kona-common-proc.workspace = true
kona-driver.workspace = true
kona-derive.workspace = true
kona-executor.workspace = true
kona-mpt.workspace = true
kona-preimage.workspace = true

risc0-zkvm.workspace = true
risc0-zkvm-platform.workspace = true

serde.workspace = true
tracing.workspace = true