name: CI

on:
  merge_group:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# OIDC access to S3 caching bucket
permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_TOOLCHAIN_VERSION: 1.85.0
  RISC0_MONOREPO_REF: "main"

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: risc0/risc0/.github/actions/rustup@main
      - name: cargo fmt kailua
        run: |
          cargo fmt --all --check
      - name: cargo fmt kailua-fpvm
        run: |
          cargo fmt --all --check --manifest-path build/risczero/fpvm/Cargo.toml
